did task
lambdafrela/parser pull request #14
Opened 2016-11-12 00:28 UTC by Yahohoo

Домашнее задание

## Описание

## Связанныые обсуждения (issues)

## Тестирование кода

## Тип изменений

- [ X] Домашнее задание (если выбрал этот пункт, удали раздел "Причины")
- [ ] Исправление ошибки (bug fix) (некритическое изменение, которое исправляет что-то, обсуждаемое в issues)
- [ ] Новая фича (new feature) (некритическое изменение, добавляющее функциональности)
- [ ] Критическое изменение (breaking change) (исправление или фича, которая сильно меняет структуру/функциональность кода)

## Чеклист:

- [X ] Мой код соответствует стилю, в котором написан весь проект.
- [ ] Мои изменения требуют изменений в документации.
- [ ] Я внес соответствующие правки в документацию.
- [ ] Я добавил тесты, проверяющие мой код.
- [ ] Все новые и существующие тесты успешно пройдены.

2016-11-12 11:42 UTC, murych requested changes
При запуске вываливается ошибка

```
Traceback (most recent call last):
  File "parser/parser.py", line 15, in <module>
    f.write(line + '\n')
TypeError: unsupported operand type(s) for +: 'Tag' and 'str'
[Finished in 3.7s with exit code 1]
[cmd: ['/usr/bin/python3', 'parser/parser.py']]
```

Попробуй посмотреть документацию к [BeautifulSoup4](https://www.crummy.com/software/BeautifulSoup/bs4/doc/), чтобы вынуть из каждой строчки с ссылкой её содержание

2016-11-13 12:23 UTC, Yahohoo commented
@murych Это я с гитом немного не то сделал) Надо сейчас перезалить

2016-11-13 15:23 UTC, murych approved these changes
Годный вариант, но интерфейс для командной строки пока не нужен :)

2016-11-13 15:23 UTC, murych commented on parser.py
> +	target_url = "http://www.livelib.ru/books/top"
это, безусловно, здорово, что появилась конструкция `try...except`, да еще и передача аргументов из командной строки, но если на вход дадут сайт, отличный от livelib, парсер не сработает, потому что на разных сайтах названия книг лежат в разных тегах. например, сайт [Readly](http://readly.ru/) хранит названия в тегах `<h3 class=blvi__title>Убить пересмешника</h3>`.

2016-11-13 15:23 UTC, murych commented on parser.py
> +        f.write(line.get_text() + '\n')
Правильное решение, хотя я каждый раз поражаюсь, откуда берутся эти 100500 способов сделать одно и то же :D

2016-11-22 23:09 UTC, closed without merging