added opportunity to transmit book names to file
lambdafrela/parser pull request #15
Opened 2016-11-12 21:38 UTC by Mikhail-Z

## Описание
Читаю данные из файла и циклом for вывожу элемент за элементом из файла

## Связанныые обсуждения (issues)

https://github.com/lambdafrela/lambda-help/blob/master/lectures/2016/11-09/README.ipynb

## Тестирование кода

## Тип изменений

- [x] Домашнее задание (если выбрал этот пункт, удали раздел "Причины")
- [ ] Исправление ошибки (bug fix) (некритическое изменение, которое исправляет что-то, обсуждаемое в issues)
- [ ] Новая фича (new feature) (некритическое изменение, добавляющее функциональности)
- [ ] Критическое изменение (breaking change) (исправление или фича, которая сильно меняет структуру/функциональность кода)

## Чеклист:

- [x] Мой код соответствует стилю, в котором написан весь проект.
- [ ] Мои изменения требуют изменений в дркументации.
- [ ] Я внес соответствующие правки в документацию.
- [ ] Я добавил тесты, проверяющие мой код.
- [ ] Все новые и существующие тесты успешно пройдены.

2016-11-13 08:37 UTC, murych submitted a review, later dismissed
имеет смысл избавиться от второго цикла, для этого можно почитать документацию к BeautifulSoup :)

2016-11-13 15:28 UTC, murych commented on parser.py
> +        for elem in book:
Необходимо избавиться от второго вложенного цикла, ибо становится нечитабельно и иррационально. Имеет смысл почитать документацию по [Beautiful Soup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)

2016-11-13 15:29 UTC, murych requested changes
Слишком сложное решение

2016-11-13 15:35 UTC, murych commented on parser.py
> +
кстати, согласно того же [pep8](http://legacy.python.org/dev/peps/pep-0008/), если хочешь визуально отделять блоки кода друг от друга, то делать это надо одной пустой строкой. две пустые строки надо ставить перед декларацией функциий и классов

2016-11-13 20:34 UTC, plaguedo commented
Да, да. Murych верно подметил. Из-за второго цикла читабельность/понимание кода уменьшается. Избавиться от него можно очень просто. book в нашем случае является объектом Tag (местным объектом, созданным Супом/описанным в Супе), поэтому, скорее всего, из-за ошибки "Tag + string = аяяй" был использован второй цикл. Но т.к. благодаря документации мы можем узнать, что у Tag есть атрибут string, то мы восхитительны и фигачим цикл так:

    for book in top_titles:
        f.write(book.string+'\n')

2016-11-13 20:51 UTC, murych commented
@plaguedo откуда столько способов берется? я искренне считал (да и сейчас считаю), что можно использовать `book.text` :smile:

2016-11-13 21:49 UTC, Mikhail-Z commented
Изменил все как вы сказали.

2016-11-14 08:07 UTC, murych approved these changes

2016-11-22 23:09 UTC, closed without merging