Write rewiew pls
lambdafrela/parser pull request #24
Opened 2016-12-23 02:19 UTC by Yahohoo

## Описание

## Связанныые обсуждения (issues)

## Причины

## Тестирование кода

## Тип изменений

- [ ] Домашнее задание (если выбрал этот пункт, удали раздел "Причины")
- [ ] Исправление ошибки (bug fix) (некритическое изменение, которое исправляет что-то, обсуждаемое в issues)
- [ ] Новая фича (new feature) (некритическое изменение, добавляющее функциональности)
- [ ] Критическое изменение (breaking change) (исправление или фича, которая сильно меняет структуру/функциональность кода)

## Чеклист:

- [ ] Мой код соответствует стилю, в котором написан весь проект.
- [ ] Мои изменения требуют изменений в дркументации.
- [ ] Я внес соответствующие правки в документацию.
- [ ] Я добавил тесты, проверяющие мой код.
- [ ] Все новые и существующие тесты успешно пройдены.

2016-12-25 00:08 UTC, murych commented
опять мои коммиты в реквесте? :smile:

2016-12-29 20:16 UTC, murych commented
@Yahohoo опиши процесс запуска этого под виндой, пока что, несмотря на раскомментирование строк с заданием path, я получаю только это:

```
Traceback (most recent call last):
  File "C:/dist/github/parser/Interface.py", line 5, in <module>
    from PyQt5.QtWidgets import (QWidget, QPushButton, QLineEdit,
ImportError: DLL load failed: The specified module could not be found.
```

2016-12-29 20:47 UTC, murych requested changes
- [x] переименуй `Interface.py`  в `parser.py` или вынести конструкцию 
```python
if __name__ == '__main__':
	app = QApplication(sys.argv)
	ex = Window()
	sys.exit(app.exec_())
```
в отдельный от интерфейса файл :)

- [x] верни `.gitignore` и `README.md` хотя бы, чтобы в репозитории мусор не копился

- [ ] создай файл `requirements.txt` , в котором на каждой строчке перечисли, какие библиотеки используешь ([подробнее о том, зачем](https://www.dabapps.com/blog/introduction-to-pip-and-virtualenv-python/)), например:
```
requests
PyQt5
BeautifulSoup4
```

- [ ] если кодишь в PyCharm, то не поленись, нажми `ctrl+alt+L`, чтобы код пришел в соответствие с pep8

(это все для уменьшения количества конфликтов при слиянии)

2016-12-29 20:47 UTC, murych commented on backend.py
> +        # Возвращает авторов и названия книг под тегами
Описание функций лучше оформлять в шесть двойных кавычек:
```python
"""
Возвращает авторов и названия книг под тегами
аргументы для поиска в супе определены в классах сайтов ниже
"""
```

2016-12-29 20:47 UTC, murych commented on backend.py
> +        self.name = re.findall('(\w+\.\w+)\/', self.url)[0]
в regex'е небольшая ошибка, надо убрать обратный слэш: `(\w+\.\w+)/`

2016-12-29 20:47 UTC, murych commented on backend.py
> +        if self.cashed_data:
здесь было бы уместнее использовать конструкцию `try...except`, ожидая, например, [AttributeError](https://docs.python.org/3/library/exceptions.html#AttributeError) (поправь, если ошибаюсь, как проверишь):
```python
try:
   return self.cashed_data
except AttributeError:
   # тело else
```

2017-01-04 21:47 UTC, murych commented on backend.py
> +        self.name = urlparse(self.url).netloc
:clap:

2017-01-04 22:08 UTC, murych commented
@Yahohoo , крч, по существу
- сделай `requirements.txt`, как я писал выше
- добавь в README инструкцию по созданию виртуального окружения и установки модулей из текстового файла (я через `anaconda` делал, мне так привычнее уже)
и будет годнота :ok_hand:

2017-01-06 20:58 UTC, Yahohoo commented on backend.py
> +        if self.cashed_data:
Все работает, cashed_data инициуриется в __init__ Site

2017-01-06 20:58 UTC, Yahohoo commented on backend.py
> +        # Возвращает авторов и названия книг под тегами
Шесть кавычек добавлю. Просто думал, что это обязательно должно быть описание с доктестами.

2017-01-06 21:09 UTC, Yahohoo commented
@murych а инструкция должна содержать и venv и conda варианты создания окружения?

2017-01-07 17:43 UTC, Yahohoo commented on backend.py
> +        # Возвращает авторов и названия книг под тегами
@murych Вообще появился вопрос, а можно ли и нужно ли создавать доктесты для функций в классах, особенно, если используется делегирование?

2017-01-07 22:33 UTC, murych commented
@Yahohoo инструкцию напиши хотя бы для `virtualenv`. Там ничего сложного нет, просто для "академических" целей. Пиши на русском, тут все свои :)

2017-01-07 22:34 UTC, murych commented on backend.py
> +        # Возвращает авторов и названия книг под тегами
@Yahohoo можно просто описание функции, в общем-то оставить

2017-02-26 20:50 UTC, murych approved these changes

2017-02-26 20:52 UTC, merged